name: DigitSingleStep

### Trajectory settings
  # number of time nodes to evaluate constraints
N: 14

  # distribution of the time nodes
time_discretization: Chebyshev # Chebyshev, Uniform

  # degree of the Bezier curve (as the desired trajectory)
degree: 5

### Gait behavior settings
  # step height (in the middle of the gait)
  # suggested range: 0.05 ~ 0.3
step_height: 0.3

  # total step length from the beginning to the end of the gait
  # walk backward if negative
  # suggested range: 0 - 0.7
step_length: 0.7

### Ipopt Optimization settings
  # terminal condition 1: optimality tolerance
tol: 1e-5

  # terminal condition 2: constraint violation tolerance
constr_viol_tol: 1e-4

  # terminal condition 3: maximum wall time
max_wall_time: 1000.0

  # terminal condition 4: maximum number of iterations
max_iter: 200

  # scale the objective function
obj_scaling_factor: 1e-3

  # print level
print_level: 5 # 0: no output, 5: detailed output that is usually enough for tuning parameters

  # mu_strategy
mu_strategy: adaptive # "adaptive" for more aggressive attempts, "monotone" for more conservative convergence

  # linear solver (HSL)
linear_solver: ma57 # ma27, ma57, ma86, ma97, pardiso

  # turn on gradient check or not
gredient_check: false